### ISSUE TITLE
Перезаписать скринкасты для первого полета

### ISSUE THREAD

**Issue by breslavsky** [breslavsky/hello-cypress#1]
- [x] команда `install i cypress@9 --save-dev`
- [x] `Cypress.on('uncaught:exception', () => false)` добавляем в сам файл теста

**Comment by Vladimir4932** [comment]
@breslavsky  Done. Test is working.

**Comment by Vladimir4932** [comment]
@breslavsky Can you help me? I can't do a convertation  a video from `.mov` format to `mp4` format. I'm using `ffmpeg` for this. 
<img width="400" alt="Screenshot 2022-11-04 at 13 21 55" src="https://user-images.githubusercontent.com/92365254/199973648-5652909d-5770-4498-9e62-1522ead23662.png">

**Comment by Vladimir4932** [comment]
@breslavsky  please assist.

# Comment doesn't pulling

I recorded a new video and have done the commit, but it tries to push about 1 hour. I don't see my commit in GitHub.  What can I do?

<img width="400" alt="Screenshot 2022-11-04 at 16 56 04" src="https://user-images.githubusercontent.com/92365254/200021803-19b06dd2-54ec-4a63-8bbe-1bbfa0c8ad7e.png">

**Comment by Vladimir4932** [comment]
done

**Comment by Vladimir4932** [comment]
@breslavsky check please

**Comment by breslavsky** [comment]
Что проверить? Где ссылка на пулрегвест?

**Comment by Vladimir4932** [comment]
@breslavsky  https://github.com/breslavsky/hello-cypress/commit/57e02d6a8aedaff07f09286c42c337fbe7457a6d
