### ISSUE TITLE
Туториала — фейк дата в тестах

### ISSUE THREAD

**Issue by breslavsky** [breslavsky/hello-cypress#2]
Пройти туториал https://md.epic1h.com/fake_data

Проблемы и вопросы пишите в сообщениях.

# Как задать вопрос?

Что бы ваш вопрос получил **качественный ответ**, он должен быть хорошо **сформулирован** и **оформлен**.

Вы всегда должны думать 🧡 о тех, с кем работаете или учитесь.

Когда вы формулируете вопрос, используйте принцип: **Что? Где? Когда? Зачем?**

Для оформления сообщения не забывайте форматировать 🔥 код в Markdown!

# Пример качественного вопроса

**Ошибка ввода текста в поле username на форме регистрации**

Коллеги, пишу на Cypress функциональный тест формы регистрации https://demo.realworld.io/#/register 
```js
cy.visit('https://demo.realworld.io/#/register');
cy.get('input').type('test');
```

Ожидаю, что Cypress должен ввести текст **test** в поле **username.**

Однако, в ходе выполнения получаю ошибку 😞 в Cypress:
```js
cy.type() can only be called on a single element. Your subject contained 2 elements!
```

Подскажите, в чем причина? Заранее благодарю 🙏

# Исходник Markdown

~~~markdown
**Ошибка ввода текста в поле username на форме регистрации**

Коллеги, пишу на Cypress функциональный тест формы регистрации https://demo.realworld.io/#/register 
```js
cy.visit('https://demo.realworld.io/#/register');
cy.get('input').type('test');
```

Ожидаю, что Cypress должен ввести текст **test** в поле **username.**

Однако, в ходе выполнения получаю ошибку 😞 в Cypress:
```js
cy.type() can only be called on a single element. Your subject contained 2 elements!
```

Подскажите, в чем причина? Заранее благодарю 🙏
~~~

**Comment by adlan-prog** [comment]
тест

**Comment by adlan-prog** [comment]
Ошибка  в функции **generateFakeUser** при создании строки **about:** .
 1. пишу ```about: faker.about(),```
 2. или так about: ```faker.datatype.about(),``` 
 3.и ```about: faker.about.about();```
Но компилятор пишет вот так

![1](https://user-images.githubusercontent.com/88831267/199551054-9cd951be-93bb-4a3f-bf9f-562c1019164f.png)

**Comment by adlan-prog** [comment]
> А разве `about()` есть в **API** Faker https://fakerjs.dev/api/ ?
> 
> Я не нашел.

Нет. я тоже не сразу понял. поставил туда ```about: faker.lorem.text(),``` **вот это**

**Comment by adlan-prog** [comment]
тут нет строки 
```cy.visit('realworld.io')```
та ки должно быть?

![2](https://user-images.githubusercontent.com/88831267/199557498-ee1682bd-4a17-410f-b361-811a6f10a7a4.png)

**Comment by breslavsky** [comment]
Открой сайт в самом начале теста перед вызовом `login()`

**Comment by breslavsky** [comment]
Moved to https://github.com/breslavsky/hello-cypress/discussions/13
