### ISSUE TITLE
Draw wireframes & design form memes for EN

### ISSUE THREAD

**Issue by breslavsky** [breslavsky/hello-cypress#23]
@NicroN37 please check https://md.epic1h.com/memes_teach

**Comment by NicroN37** [comment]
wireframes

![image](https://user-images.githubusercontent.com/117467298/205680042-8396c13a-78df-44fe-b4c1-e6c4855093bc.png)
![image](https://user-images.githubusercontent.com/117467298/205680102-e14cd5fe-02b4-4eaf-bdc4-007d16e34690.png)

Prototype

https://www.figma.com/proto/SfE2QaVd2kBFuulwpJ7OMN/Memes-for-EN?page-id=0%3A1&node-id=40%3A210&viewport=-298%2C-1599%2C0.67&scaling=scale-down&starting-point-node-id=38%3A135

**Comment by breslavsky** [comment]
It is very cool! In wireframes let's add something like this https://thenounproject.com/icon/yao-ming-105260/

**Comment by NicroN37** [comment]
> It is very cool! In wireframes let's add something like this https://thenounproject.com/icon/yao-ming-105260/

![image](https://user-images.githubusercontent.com/117467298/205862885-b9fb61f4-2905-4ff2-b3d9-852406487cd9.png)
