### ISSUE TITLE
Add links to syllabus

### ISSUE THREAD

**Issue by breslavsky** [breslavsky/hello-cypress#27]
https://github.com/breslavsky/hello-cypress/blob/main/README.md?plain=1

Check as example `click npm_init`

**Comment by Vladimir4932** [comment]
https://github.com/breslavsky/hello-cypress/compare/main...27-add-links-to-syllabus
@breslavsky check, please. I've got a problem with render. 

<img width="400" alt="Screenshot 2023-01-05 at 15 37 15" src="https://user-images.githubusercontent.com/92365254/210805613-bf1e4a5e-3386-47a0-be30-e8031b7a2269.png">   

can you help me identify that problem?

**Comment by breslavsky** [comment]
Record video.

**Comment by breslavsky** [comment]
Also you can use https://mermaid.live/edit

**Comment by Vladimir4932** [comment]
https://www.awesomescreenshot.com/video/13764522?key=bb44a39002708c403dc5b207ac130256

**Comment by Vladimir4932** [comment]
I found. Thanks.

**Comment by Vladimir4932** [comment]
@breslavsky  I didn't find part of video with **[data-cy]** description. We can use link to page [data attributes](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) about. What do you think?

**Comment by Vladimir4932** [comment]
https://github.com/breslavsky/hello-cypress/compare/main...27-add-links-to-syllabus  

@breslavsky  check please

**Comment by breslavsky** [comment]
Good, in future, please assign to me pull request. Please check that you have no conflicts ;-)
